### ISSUE TITLE
Can audio only download be supported?

### ISSUE THREAD

**Issue by palla89** [hyeonsangjeon/youtube-dl-nas#10]
Hi, thank you for your work, it's awesome!
It would be so great to also have a "bestaudio" download feature! 
I know that youtube-dl supports this so maybe it wouldn't be hard to implement?

**Comment by palla89** [comment]
Did it! Pull Request #11 
Waiting for a merge if that's ok for you!

**Comment by hyeonsangjeon** [comment]
Thanks. I have merged.

**Comment by hyeonsangjeon** [comment]
I found script below example,

best quality mp3
youtube-dl -x --audio-format "mp3" --audio-quality "0" "url"

320k quality mp3
youtube-dl -x --audio-format "mp3" --audio-quality "320k" "url"

**Comment by thotmail** [comment]
pull #18 takes care of the mp3 thing

**Comment by hyeonsangjeon** [comment]
i will resolve it
