### ISSUE TITLE
Synology Docker: how to change the port?

### ISSUE THREAD

**Issue by dan-the-man-nz** [hyeonsangjeon/youtube-dl-nas#2]
Hi

8080 is already in use by another docker image

i tried adding a enviroment variable like this

host:guest  with value of    8181:8181

but it doesnt change the port, any suggestions? thanks

**Comment by hyeonsangjeon** [comment]
The guest port is the application port in the docker and is fixed at 8080. You can change the Synology HOST server port. Here's how to change it.

-p 8181:8080
