### ISSUE TITLE
특정 URL 이 다운로드가 안되는 이슈

### ISSUE THREAD

**Issue by urstory** [hyeonsangjeon/youtube-dl-nas#23]
https://www.youtube.com/watch?v=_zRD5UREP7U

장범준 노래가 있는 URL인데요. 해당 URL이 다운로드가 되지 않습니다.

터미널에서 pip install -U youtube-dl 도 실행하였습니다.

**Comment by hyeonsangjeon** [comment]
youtube-dl has been updated. It goes well. I will resolve.
