### ISSUE TITLE
안녕하세요. 혹시 이 애러는 왜 생기는건지 알수 있을까요?

### ISSUE THREAD

**Issue by arithxp** [hyeonsangjeon/youtube-dl-nas#4]
유튜브 영상을 받으려고하면 아래와 같은 오류가 발생하는데 어떻게 해야하나요?

> 2019-01-30 19:17:22,stdout," (caused by ExtractorError(\"Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
"
2019-01-30 19:17:22,stdout,youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>
>2019-01-30 19:17:22,stdout,    raise ExtractorError('Could not find JS function %r' % funcname)
>
>2019-01-30 19:17:22,stdout,"  File \"/usr/local/lib/python3.6/site-packages/youtube_dl/jsinterp.py\", line 245, in extract_function
"
>2019-01-30 19:17:22,stdout,    initial_function = jsi.extract_function(funcname)
>
>2019-01-30 19:17:22,stdout,"  File \"/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py\", line 1200, in _parse_sig_js
"
>2019-01-30 19:17:22,stdout,    res = self._parse_sig_js(code)
>
>2019-01-30 19:17:22,stdout,"  File \"/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py\", line 1133, in _extract_signature_function
"
>2019-01-30 19:17:22,stdout,"    video_id, player_url, s
"
>2019-01-30 19:17:22,stdout,"  File \"/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py\", line 1225, in _decrypt_signature
"
>2019-01-30 19:17:22,stdout,[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):

**Comment by hyeonsangjeon** [comment]
binary 실행파일이 업데이트 되었나보네요. 
예제 URI 하나만 알려주실수 있을까요?

**Comment by arithxp** [comment]
> 
> 
> binary 실행파일이 업데이트 되었나보네요.
> 예제 URI 하나만 알려주실수 있을까요?

시간이 지나서 링크가 기억나질 않네요.. ㅜㅜ
다만 궁금한게 하나 있습니다.

.incomplete 폴더에 받고나서 합쳐서 옮기는 방식인걸로 보여지는데요.
플레이 리스트가 10개라고 했을때 5개받다가 에러로 멈춰서 다시 시도하면 5개부터 이어받나요?
아니면 받고나서 덮어쓰기 하나요?

**Comment by hyeonsangjeon** [comment]
순서대로 큐에서 처리하는거라 5번째 에러라면 5번째 스레드 에러 exception 후 6번째 워커 정상 처리하게 되어있습니다.

**Comment by hyeonsangjeon** [comment]
바이너리 파일 재업데이트해서 빌드했습니다. 컨테이너 다시 pull 받아서 기동해보세요.  
https://github.com/rg3/youtube-dl/issues/18873

**Comment by hyeonsangjeon** [comment]
바이너리 파일 재업데이트해서 빌드했습니다. 컨테이너 다시 pull 받아서 기동해보세요.
rg3/youtube-dl#18873
이상 있으시면 코맨트 달아주세요~
이 issue는 2일 후 close하겠습니다.

**Comment by hyeonsangjeon** [comment]
바이너리 파일 재업데이트해서 빌드했습니다. 컨테이너 다시 pull 받아서 기동해보세요.
rg3/youtube-dl#18873
이상 있으시면 코맨트 달아주세요~
이 issue는 2일 후 close하겠습니다.

**Comment by arithxp** [comment]
> 
> 
> 순서대로 큐에서 처리하는거라 5번째 에러라면 5번째 스레드 에러 exception 후 6번째 워커 정상 처리하게 되어있습니다.

그러면 10개중 5개 받고 애러로 멈춰서 .incomplete폴더에 6번째 영상 받던게 들어있고
/downfolder에 5개의 영상이 있는 상태에서
나스 껐다켠후에 다시 시도해도 6번째부터 받는다고 이해하면 될까요?


아 그리고 안됐던 영상이 무었이었는지 기억은 안나지만 다른 영상들은 애러없이 잘됩니다.
감사합니다.

**Comment by hyeonsangjeon** [comment]
10개의 큐에서 5번째 스레드가 에러만 발생한다면 아래와 같이 파이프라인이 처리됩니다. 스레드가 죽으면 다시 살려요. 
1(O)->2(O)->3(O)->4(O)->5(X)->6(O)->7(O)->8(O)->9(O)->10(O)

아래 에러가 발생했던 url을 메일로 주시면 파악하기 쉬울거같습니다. 
감사합니다.
