### ISSUE TITLE
url access failure

### ISSUE THREAD

**Issue by xdeng** [hyeonsangjeon/youtube-dl-nas#8]
My download failed.

[youtube] BBVLj_PSsZ8: Downloading webpage
03:18:46 | [youtube] BBVLj_PSsZ8: Downloading video info webpage
03:18:46 | [youtube] BBVLj_PSsZ8: Downloading js player vflBMETJb
03:18:47 | [0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
03:18:47 | File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
03:18:47 | video_id, player_url, s
03:18:47 | File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
03:18:47 | res = self._parse_sig_js(code)
03:18:47 | File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
03:18:47 | jscode, 'Initial JS player signature function name', group='sig')
03:18:47 | File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
03:18:47 | raise RegexNotFoundError('Unable to extract %s' % _name)
03:18:47 | youtube_dl.utils.RegexNotFoundError: Unable to extract [0;34mInitial JS player signature function name[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
03:18:47 | (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hyeonsangjeon** [comment]
'pip install -U youtube-dl' command batch runs at 00 once a day in this app.
If not working suddenly try manually running pip install -U youtube-dl in terminal.

**Comment by hyeonsangjeon** [comment]
youtube-dl has been updated. It goes well. I will resolve
